language: objective-c
osx_image: xcode11
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=OAuthSwift-Alamofire.xcodeproj
    - IOS_FRAMEWORK_SCHEME="OAuthSwift-Alamofire"
    - MACOS_FRAMEWORK_SCHEME="OAuthSwift-AlamofireOSX"
    - IOS_SDK=iphonesimulator13
    - MACOS_SDK=macosx10.15
  matrix:
    - DESTINATION="OS=13.0,name=iPhone 8" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" RUN_TESTS="NO"
    - DESTINATION="arch=x86_64" SCHEME="$MACOS_FRAMEWORK_SCHEME" SDK="$MACOS_SDK" RUN_TESTS="YES"
before_install:
  - gem install xcpretty --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - carthage checkout
  - carthage build --no-skip-current
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
